# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Envoy' do
	pod 'Realm', '~> 0.97.0'
	pod 'JSONModel', '~> 1.1.2'
end

target 'EnvoyTests' do
	pod 'Realm/Headers'
end

