# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Hexlist' do
	pod 'Realm', '~> 0.97.0'
	pod 'JSONModel', '~> 1.1.2'
	pod 'box-ios-sdk', '~> 1.0.11'
	pod 'Google-API-Client', '~> 1.0.422'
	pod 'ChameleonFramework', '~> 2.0.6' 
end

target 'HexlistTests' do
	pod 'Realm/Headers'
end

